os: Visual Studio 2017

platform:
  - x64
  - x86
 
configuration:
  - Release
  - Debug

before_build:
  - cmake .
  - dir
  - cd src && dir && cd ..
  - cd test && dir && cd ..

build:
  project: $(APPVEYOR_BUILD_FOLDER)\Euclide.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\euclide_tests.exe'