os: Visual Studio 2017

platform:
  - x64
  - x86
 
configuration:
  - Release
  - Debug

install: off

before_build:
  - cmake .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\euclide_tests.exe'