os: Visual Studio 2017

platform: x64
 
configuration:
  - Release
  - Debug

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\Euclide.sln

after_build:
  - dir bin
  - cd src && dir Release && cd ..
  - cd test && dir Release && cd ..

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\euclide_tests.exe'