os: Visual Studio 2017

platform: x64
 
configuration:
  - Release
  - Debug

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" .
  - dir
  - cd src && dir && cd ..
  - cd test && dir && cd ..

build:
  project: $(APPVEYOR_BUILD_FOLDER)\Euclide.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\euclide_tests.exe'